# Generated by Django 2.2 on 2020-12-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='prof_photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
