# Generated by Django 2.2 on 2020-12-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_shop_app', '0002_auto_20201211_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
