# Generated by Django 2.2 on 2020-12-14 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_shop_app', '0004_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bottle_shop_app.User')),
                ('user_likes', models.ManyToManyField(related_name='liked_messages', to='bottle_shop_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=20)),
                ('vintage', models.CharField(max_length=6)),
                ('varietal', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=250)),
                ('tasting_notes', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to='bottle_shop_app.User')),
            ],
        ),
    ]
