# Generated by Django 2.2 on 2020-12-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_shop_app', '0005_bottle_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='1930-01-01', max_length=8),
        ),
    ]
