# Generated by Django 2.2 on 2020-12-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_shop_app', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='bottle_photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
